[package]
name = "simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal-i2c = { path = "../embedded-hal-i2c" }
tokio = { version = "1.44.2", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.44.2", features = ["rt", "macros", "time"] }
